//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ws_comida_rapida.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingrediente_en_comida
    {
        public int id { get; set; }
        public int id_comida { get; set; }
        public int id_ingrediente { get; set; }
    
        public virtual Comida Comida { get; set; }
        public virtual Ingrediente Ingrediente { get; set; }
    }
}
